Add a mercurial source
lilydjwg/nvchecker pull request #170
Opened 2020-11-17 17:31 UTC by felixonmars

This uses the json api of mercurial repositories. Verified to work on
the following hosting sites:

www.mercurial-scm.org/repo
hg.code.sf.net
hg.nginx.org
hg.mozilla.org

2020-11-18 04:34 UTC, lilydjwg requested changes

2020-11-18 04:34 UTC, lilydjwg commented on nvchecker_source/mercurial.py
> +  url = conf.get('mercurial') + '/json-tags'
Since the `mercurial` key is required, we'd better `conf['mercurial']` and get a `KeyError` if not given.

2020-11-18 04:34 UTC, lilydjwg commented on docs/usage.rst
> +
Mention `hg` somewhere? I bet users will try to search `hg` for its documentation.

2020-11-18 04:34 UTC, lilydjwg commented on nvchecker_source/mercurial.py
> +  return version
Will we support a `latest_tag` option? I see timestamps are returned too.

2024-03-09 11:19 UTC, merged

2024-03-09 20:19 UTC, felixonmars commented
Oops. Indeed I was planning to address the mentioned issues, but it went lost in my TODO. Sorry!